<a href="https://colab.research.google.com/github/JakeOh/202007_itw_bd18/blob/master/lab_python/python40_ndarray_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# 0 이상 10 이하의 짝수들로 이루어진 1차원 배열(ndarray) 생성, 출력
arr = np.arange(0, 11, 2, dtype=np.int32)
print(arr)

[ 0  2  4  6  8 10]


In [5]:
# numpy.ndarray의 인덱스는 파이썬의 list의 인덱스와 마찬가지로 0부터 시작.
# numpy.ndarray는 list와 마찬가지로 음수 인덱스를 사용할 수 있음.
print(arr[0])
print(arr[5])
print(arr[-1])

0
10
10


In [11]:
# 범위 연산자(:)을 사용한 슬라이싱(slicing) - start:end
# start <= index < end 범위의 원소들을 선택
# start를 생략하면, 0부터 시작.
# end를 생략하면, 마지막 원소까지 선택.
print(arr[0:3])
print(arr[2:4])
print(arr[:3])
print(arr[2:])
print(arr[:])
print(arr[-3:])

[0 2 4]
[4 6]
[0 2 4]
[ 4  6  8 10]
[ 0  2  4  6  8 10]
[ 6  8 10]


In [14]:
# 배열과 비슷한 객체(list, tuple, array)를 사용한 indexing - fancy indexing
print(arr)
print(arr[[1, 3, 5]])  # 홀수 인덱스에 있는 원소들로 이루어진 배열
print(arr[[0, 2, 4]])  # 짝수 인덱스에 있는 원소들로 이루어진 배열

[ 0  2  4  6  8 10]
[ 2  6 10]
[0 4 8]


In [15]:
# boolean indexing: 논릿값(True, False)들의 리스트(튜플, 배열)를 사용한 indexing
indexer = [True, True, False, False, True, False]
print(arr[indexer])

[0 2 8]


In [21]:
# 0 이상 10 이하의 정수 난수 10개로 이루어진 1차원 배열 생성, 출력
arr = np.random.randint(0, 11, size=10)
print(arr)

# 위에서 만든 배열에서 짝수들로만 이루어진 배열을 만들어서 출력.
# evens = [x for x in arr if x % 2 == 0]
print(arr % 2)  #> 1차원 배열
print(arr % 2 == 0)  #> 1차원 배열

evens = arr[arr % 2 == 0]
print(evens)

[8 9 6 5 7 2 9 3 7 1]
[0 1 0 1 1 0 1 1 1 1]
[ True False  True False False  True False False False False]
[8 6 2]


In [22]:
# boolean indexing에서는 Python의 논리 연산자(and, or, not)을 사용할 수 없음!
# 대신에, &, |, ~ 연산자를 사용하고, 연산 순서를 명시하기 위해서 반드시 ()를 사용해야 함!

# 0 이상 20 미만의 정수 난수 10개를 갖는 배열(array) 생성, 출력
arr = np.random.randint(0, 20, size=10)
print(arr)

# 배열의 원소들 중 5 이상이고 15 이하인 숫자들의 배열을 출력.
print(arr[(arr >= 5) & (arr <= 15)])

# 배열의 원소들 중 5 미만이거나 15 이상인 숫자들의 배열을 출력.
print(arr[(arr < 5) | (arr >= 15)])

[10 19  2  8 16  5  5 16  3  2]
[10  8  5  5]
[19  2 16 16  3  2]


In [23]:
array = np.arange(12).reshape((3, 4))
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
# Python 2차원 list: list[i][j]
# NumPy 2차원 array: array[i][j], array[i, j]
print(array[1][2], array[1, 2])

# 2차원 배열에서도 범위 연산자를 사용할 수 있음: array[a:b, c:d]
print(array[0:2, :])
print(array[:, 1:3])
print(array[:, 1])  #> 1차원 배열!!

# 2차원 배열에서도 fancy indexing을 사용할 수 있음: array[[], []]
print(array[:, [0, 2]])
print(array[:, [1]])  #> 2차원 배열!!

6 6
[[0 1 2 3]
 [4 5 6 7]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[1 5 9]
[[ 0  2]
 [ 4  6]
 [ 8 10]]
[[1]
 [5]
 [9]]


In [32]:
print(array)
print(array[[0, 2], :])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [33]:
print(array)
print(array[[0, 2], [1, 3]])  # [0, 1], [2, 3] 인덱스에 있는 원소로 이루어진 1차원 배열!!!

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1 11]


In [35]:
# boolean indexing
print(array)
print(array[array % 2 == 0])  #> 1차원 배열!!

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  2  4  6  8 10]


In [39]:
names = np.array(['aa', 'bb', 'cc'])
print(names)
print(names[names == 'bb'])
print(names == 'bb')

print(array[[False, True, False], :])
print(array[names == 'bb', :])

['aa' 'bb' 'cc']
['bb']
[False  True False]
[[4 5 6 7]]
[[4 5 6 7]]
