<a href="https://colab.research.google.com/github/JakeOh/202007_itw_bd18/blob/master/lab_python/python38_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python list 타입

In [6]:
numbers1 = [1, 2, 3, 5]
numbers2 = [4, 5, 8, 9]

In [7]:
numbers1 + numbers2
# list에서 + 연산은 두 개의 리스트를 이어주는 기능(concatenate)

[1, 2, 3, 5, 4, 5, 8, 9]

In [8]:
numbers1.extend(numbers2)
numbers1

[1, 2, 3, 5, 4, 5, 8, 9]

In [ ]:
numbers1 = [1, 2, 3, 5]
numbers2 = [4, 5, 8, 9]
# numbers1 - numbers2
# TypeError: list는 - 연산을 제공하지 않음!

In [12]:
# list * list 정의되어 있지 않음!
# [1, 2, 3] * [2, 3, 4]

# list * 숫자, 숫자 * list: list의 원소들을 숫자만큼 반복해서 리스트의 크기를 늘림.
[1, 2, 3] * 2

[1, 2, 3, 1, 2, 3]

In [ ]:
# list / list, list % list, list // list 정의되어 있지 않음!
# [1, 2, 3] / [4, 5, 6]

# list / 숫자, 숫자 / list 정의되어 있지 않음!

In [17]:
def add_vector(v1, v2):
    """v1, v2: 숫자들을 원소로 갖는 1차원 리스트(list). 원소의 개수(len)가 같음.
    각 원소들끼기(element-wise) 더한 값들로 만들어진 리스트를 생성해서 리턴.

    >>> add_vector([1, 2, 3], [2, 3, 4])
    [3, 5, 7]
    """
    if len(v1) != len(v2):
        raise ValueError('v1과 v2는 길이가 같아야 합니다!')

    n = len(v1)
    # result = []
    # for i in range(n):  # 0, 1, 2, ..., n-1
    #     plus = v1[i] + v2[i]
    #     result.append(plus)
    result = [v1[i] + v2[i] for i in range(n)]

    return result

In [ ]:
add_vector([1, 2, 3], [1, 2])
#> ValueError 발생

In [18]:
add_vector([1, 2, 3], [2, 3, 4])

[3, 5, 7]

In [21]:
def add_vector2(v1, v2):
    if len(v1) != len(v2):
        raise ValueError('v1과 v2는 길이가 같아야 합니다!')

    # result = []
    # for x, y in zip(v1, v2):
    #     plus = x + y
    #     result.append(plus)
    result = [x + y for x, y in zip(v1, v2)]

    return result

In [22]:
add_vector2([1, 2, 3], [2, 3, 4])

[3, 5, 7]

In [25]:
def scalar_multiply(v, n):
    """v: 숫자들을 원소로 갖는 1차원 리스트. n: 숫자.
    리스트 v의 각 원소들에 n을 곱한 값들로 만들어진 리스트를 반환.

    >>> scalar_multiply([1, 2, 3], 3)
    [3, 6, 9]
    """
    result = [x * n for x in v]
    return result

In [26]:
scalar_multiply([1, 2, 3], 3)

[3, 6, 9]

In [27]:
def vector_multiply(v1, v2):
    """v1, v2: 숫자들을 원소로 하는 1차원 리스트. v1과 v2의 길이는 같음.
    두 리스트 v1과 v2의 같은 인덱스에 있는 원소들(element-wise)끼리의 곱을 원소로 갖는 리스트를 반환.

    >>> vector_multiply([1, 2, 3], [2, 3, 4])
    [2, 6, 12]
    """
    result = [x * y for x, y in zip(v1, v2)]
    return result

In [28]:
vector_multiply([1, 2, 3], [2, 3, 4])

[2, 6, 12]

In [37]:
def vector_dot(v1, v2):
    """v1, v2: 숫자를 원소로 갖는 1차원 리스트. v1과 v2의 길이는 같음.
    같은 인덱스의 원소들끼리의 곱들의 합을 반환.
    v1 = [x1, x2, ..., xn], v2 = [y1, y2, ... yn].
    result = x1 * y1 + x2 * y2 + ... + xn * yn 반환.

    >>> vector_dot([1, 2, 3], [2, 3, 4])
    20
    """
    if len(v1) != len(v2):
        raise ValueError('v1과 v2는 길이가 같아야 합니다!')

    # result = 0
    # for x, y in zip(v1, v2):
    #     result += x * y
    result = sum(x * y for x, y in zip(v1, v2))  # generator expression

    return result

In [38]:
vector_dot([1, 2, 3], [2, 3, 4])

20

# NumPy(Numerical Python)

* 배열(array: 숫자들의 리스트)을 쉽고, 빠르게 연산(+, - ,*, /, ...)하기 위한 라이브러리.
* NumPy의 대부분의 기능(함수, 메서드)들은 반복문의 기능을 가지고 있음.
* 같은 인덱스의 원소들끼리(element-wise) 연산을 수행하는 경우가 많음.
* numpy.ndarray: n-dimensional array(n차원 배열). NumPy에서 사용하는 데이터 타입(클래스)

In [39]:
import numpy as np

# 구글 Colab에 설치된 NumPy의 버전 확인
np.__version__

'1.18.5'

In [44]:
print([1, 2, 3])

array1 = np.array([1, 2, 3])  # list를 array로 변환
print(array1)
print(type(array1))

# ndarray의 속성(attribute)들
print(array1.shape)  # 각 차원(축)의 원소의 개수
print(array1.ndim)  # 차원(축) 수

[1, 2, 3]
[1 2 3]
<class 'numpy.ndarray'>
(3,)
1


In [49]:
array2 = np.array([4, 5, 9])

print(array1 + array2)  # numpy.ndarray에서 + 연산: 원소들끼리 덧셈 수행. array1.__add__(array2)
print(array1 - array2)  # array1.__sub__(array2)
print(array1 * array2)
print(array1 / array2)
print(array2 * 2)

# numpy.ndarray 클래스는 연산자 오버로딩(operator overloading)이 되어 있음.

[ 5  7 12]
[-3 -3 -6]
[ 4 10 27]
[0.25       0.4        0.33333333]
[ 8 10 18]


In [52]:
print(array1)
print(array2)
print(array1.dot(array2))  # 1*4 + 2*5 + 3*9 = 41
print(array1 @ array2) # Python 3.5 버전 이상에서만 가능.

[1 2 3]
[4 5 9]
41
41


In [55]:
# 2차원 array의 연산
print([[1, 2],
       [3, 4]])  # 2차원 리스트(list)

array1 = np.array([[1, 2], 
                   [3, 4]])  # 2차원 ndarray
print(array1)

array2 = np.array([[1, 2], 
                   [4, 3]])
print(array2)

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]
[[1 2]
 [4 3]]


In [56]:
print(array1 + array2)

[[2 4]
 [7 7]]


In [57]:
print(3 * array1)  # array1 * 3: __mul__(), 3 * array1: __rmul__()

[[ 3  6]
 [ 9 12]]


In [59]:
print(array1 @ array2)
print(array2 @ array1)

[[ 9  8]
 [19 18]]
[[ 7 10]
 [13 20]]


행렬(Matrix)의 내적(Inner Product, Dot Product)
* (n, k) @ (k, m) = (n, m)
* 연산자 왼쪽 행렬의 column 개수와 연산자 오른쪽 행렬의 row 개수가 다르면 dot product를 수행할 수 없다!
* A @ B != B @ A: 교환 법칙이 성립하지 않음.

In [65]:
array3 = np.array([[1, 2, 3],
                   [2, 3, 4]])  # (2, 3) shape
print(array3.shape)

array4 = np.array([[1, 2],
                   [2, 3],
                   [3, 4]])  # (3, 2) shape
print(array4.shape)

# array3 @ array4 = shape (2, 2)
# array4 @ array3 = shape (3, 3)
print(array3 @ array4)
print(array4 @ array3)

(2, 3)
(3, 2)
[[14 20]
 [20 29]]
[[ 5  8 11]
 [ 8 13 18]
 [11 18 25]]
